//constants

export const PROJECTDATA = [
  {
    id: '1',
    name: 'maxVolunteers',
    label: '모집 인원',
    type: 'number',
    placeholder: '모집 인원을 입력하세요. (ex. 5)',
  },
  {
    id: '2',
    name: 'startDatePre',
    label: '시작 예정',
    type: 'text',
    placeholder: 'YYYY. MM. DD',
  },
  {
    id: '3',
    name: 'field',
    label: '모집 분야',
    type: 'text',
    placeholder: '모집 분야를 입력하세요.',
  },
  {
    id: '4',
    name: 'duration',
    label: '예상 기간',
    type: 'number',
    placeholder: '예상 기간을 입력하세요. (ex. 5)',
  },
  {
    id: '5',
    name: 'method',
    label: '진행 방식',
    type: 'text',
    placeholder: '온라인 / 오프라인 / 온오프라인 등',
  },
  {
    id: '6',
    name: 'newBy',
    label: '새싹 여부',
    type: 'checkbox',
  },
];

export const LANGUAGEDATA = [
  { language: 'JavaScript', icon: '🟨' },
  { language: 'TypeScript', icon: '🟦' },
  { language: 'React', icon: '⚛️' },
  { language: 'Vue', icon: '🟩' },
  { language: 'Nodejs', icon: '🟢' },
  { language: 'Python', icon: '🐍' },
  { language: 'Java', icon: '☕' },
  { language: 'Go', icon: '🔵' },
  { language: 'Spring', icon: '🍃' },
  { language: 'Django', icon: '🟩' },
  { language: 'Docker', icon: '🐳' },
  { language: 'Kubernetes', icon: '☸️' },
  { language: 'AWS', icon: '☁️' },
  { language: 'MongoDB', icon: '🍃' },
  { language: 'MySQL', icon: '🛢️' },
  { language: 'GraphQL', icon: '🟪' },
  { language: 'Git', icon: '🔴' },
];

export const CATEGORY = [
  { id: '1', label: '디자이너' },
  { id: '2', label: '프론트엔드' },
  { id: '3', label: '백엔드' },
  { id: '4', label: '데이터 분석가' },
  { id: '5', label: '기획자' },
  { id: '6', label: '모바일 개발자' },
  { id: '7', label: 'AI/ML 엔지니어' },
  { id: '8', label: 'DevOps 엔지니어' },
  { id: '9', label: '게임 개발자' },
  { id: '10', label: 'UI/UX 디자이너' },
  { id: '11', label: '풀스택 개발자' },
  { id: '12', label: '마케팅 전문가' },
  { id: '13', label: '제품 관리자 (PM)' },
  { id: '14', label: 'QA 엔지니어' },
  { id: '15', label: '블록체인 개발자' },
  { id: '16', label: '사이버 보안 전문가' },
  { id: '17', label: 'AR/VR 개발자' },
  { id: '18', label: '사운드 디자이너' },
  { id: '19', label: '영상/미디어 전문가' },
  { id: '20', label: '기술 작가' },
];
