export const MODAL_MESSAGE = {
  pass: '지원자를 합격 리스트에 추가했습니다.',
  nonPass: '지원자를 불합격 리스트에 추가했습니다.',
  equalStatus: '이미 동일한 리스트에 추가하신 상태입니다.',
  signUpSuccess: '회원가입 완료되었습니다.',
  signUpFail: '회원가입 실패하였습니다.',
  changePasswordSuccess: '비밀번호가 성공적으로 재설정 되었습니다.',
  changePasswordFail: '비밀번호 재설정에 실패하였습니다.',
  loginSuccess: '로그인 되었습니다.',
  loginFail: '가입되지 않은 계정입니다.',
  logout: '로그아웃 되었습니다.',
  myProfileSuccess: '프로필 수정이 완료되었습니다.',
  myProfileFail: '프로필 수정에 실패했습니다.',
  profileImgSuccess: '프로필 이미지가 업로드 되었습니다.',
  profileImgFail: '이미지는 5MB 이하, .png.jpg.jpeg.svg 형식만 가능합니다.',
} as const;
