export const ROUTES = {
  main: '/',
  login: '/login',
  signup: '/signup',
  changePw: '/change-password',
  home: '/main',
  createProject: '/create',
  apply: '/apply',
  projectDetail: '/project-detail',
  manageProjectsRoot: '/manage',
  manageProjectsPassNonPass: '/manage/pass-nonpass',
  mypage: '/mypage',
  mypageJoinedProjects: 'join-projects',
  mypageAppliedProjects: 'apply-projects',
  myPageNotifications: 'notifications',
  myPageActivityLog: 'activity-log',
  userpage: '/user',
  userJoinedProject: 'join-projects',
  modifyProject: '/project-modify',
  notFound: '/not-found',
  support: '/inquiry',
  FAQ: '/faq',
  notice: '/notice',
} as const;
