export const ROUTES = {
  main: '/main',
  login: '/login',
  signup: '/signup',
  changePw: '/change-password',
  home: '/',
  createProject: '/create',
  apply: '/apply',
  projectDetail: '/project-detail',
  manageProjectsRoot: '/manage',
  manageProjectsPassNonPass: '/manage/pass-nonpass',
  mypage: '/mypage',
  mypageJoinedProjects: 'joined-projects',
  mypageAppliedProjects: 'apply-projects',
  myPageNotifications: 'notifications',
  notificationsAppliedProjects: 'applied-projects',
  notificationsCheckedApplicants: 'checked-applicants',
  activityInquiries: 'inquiries',
  comments: 'comments',
  myPageActivityLog: 'activity-log',
  userpage: '/user',
  userJoinedProject: 'joined-projects',
  modifyProject: '/project-modify',
  notFound: '/not-found',
  support: '/inquiry',
  FAQ: '/faq',
  notice: '/notice',
} as const;
