export const MODAL_MESSAGE = {
  isNotLoggedIn: '로그인이 필요한 서비스입니다.',
  pass: '지원자를 합격 리스트에 추가했습니다.',
  nonPass: '지원자를 불합격 리스트에 추가했습니다.',
  waiting: '지원자를 대기리스트에 추가했습니다',
  equalStatus: '이미 동일한 리스트에 추가하신 상태입니다.',
  sendResult: '지원자들에게 이메일로 결과를 전송했어요!',
  needAuth: '권한이 없어요!',
  signUpSuccess: '회원가입 완료되었습니다.',
  signUpFail: '회원가입 실패하였습니다.',
  changePasswordSuccess: '비밀번호가 성공적으로 재설정 되었습니다.',
  changePasswordFail: '비밀번호 재설정에 실패하였습니다.',
  loginSuccess: '로그인 되었습니다.',
  loginFail: '가입되지 않은 계정입니다.',
  logout: '로그아웃 되었습니다.',
  myProfileSuccess: '프로필 수정이 완료되었습니다.',
  myProfileFail: '프로필 수정에 실패했습니다.',
  profileImgSuccess: '프로필 이미지가 업로드 되었습니다.',
  profileImgFail: '이미지는 5MB 이하, .png.jpg.jpeg 형식만 가능합니다.',
  ModifyProjectSuccess: '공고 수정이 정상적으로 완료 되었습니다.',
  ModifyProjectFail: '공고 수정을 실패 했습니다.',
  createProjectSuccess: '공고 생성을 완료 했습니다.',
  createProjectFail: '공고 생성을 실패 했습니다.',
  applyProjectSuccess: '해당 공고에 지원을 완료 되었습니다.',
  applyProjectFail: '해당 공고에 지원을 실패 되었습니다.',
  projectDetailFail: '해당 공고가 존재하지 않습니다.',
  alreadyApply: '이미 참여한/지원하신 공고 입니다.',
  noMemberToEvaluate: '평가 할 멤버가 없습니다.',
} as const;
