export const ROUTES = {
  main: '/main',
  login: '/login',
  signup: '/signup',
  changePw: '/change-password',
  home: '/',
  createProject: '/create',
  apply: '/apply',
  projectDetail: '/project-detail',
  manageProjectsRoot: '/manage',
  manageProjectsPassNonPass: '/manage/pass-nonpass',
  mypage: '/mypage',
  mypageEdit: 'edit',
  joinedProjects: 'joined-projects',
  managedProjects: 'managed-projects',
  myPageNotifications: 'notifications',
  notificationsAppliedProjects: 'applied-projects',
  notificationsCheckedApplicants: 'checked-applicants',
  activityInquiries: 'inquiries',
  comments: 'comments',
  myPageActivityLog: 'activity-log',
  userpage: '/user',
  modifyProject: '/project-modify',
  notFound: '/not-found',
  customerService: '/customer-service',
  FAQ: 'faq',
  notice: 'notice',
  noticeDetail: 'notice-detail',
  inquiry: '/inquiry',
  evaluation: '/evaluation',
  loginSuccess: '/oauth-redirect',
} as const;

export const ADMIN_ROUTE = {
  admin: '/admin',
  devPals: '/main',
  notice: '/notice',
  banner: '/banner',
  tags: '/tags',
  allUser: '/all-user',
  reports: '/reports',
  inquiries: '/inquires',
  manage: '/manage',
};
